### ISSUE TITLE
Кастомизация донатной полоски

### ISSUE THREAD

**Issue by TopherBrink** [declider/donategoal#2]
При вставке стилей из блока "Кастомизация" в OBS - стили не применяются. Причём ранее (на прошлом rgg-land'е) я спокойно свой кастомный css добавлял и все стили применялись. А теперь даже настроенный во вкладке "Кастомизация" стиль не отрабатывает (хотя по сути что то, что это).
Такое ощущение, что виджет полоски обновляется и сбрасывает стили, которые добавлены в OBS.
У стримера моего такая же история, поэтому сам полез. Думал он не то что-то делает. Но видимо нет (хотя может оба без рук).

P.S. Не знал куда написать, решил сюда.

**Comment by declider** [comment]
@TopherBrink попробуйте сейчас, выставить нужный стиль и прожать кнопку "обновить" в обсе

**Comment by declider** [comment]
Починено
